# Generated by Django 3.2.6 on 2022-07-07 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default=' ', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('birthdayDate', models.DateField(blank=True, null=True, verbose_name='dueDate')),
                ('complete', models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=7)),
                ('tag', models.CharField(default='', max_length=1000)),
                ('owner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
